### ISSUE TITLE
Ruby bindings use keywords as variables

### ISSUE THREAD

**Issue by rfestag** [zeromq/czmq#1062]
I am trying to play with the Ruby bindings that are in this repository, and found that there are at least a few instances where the variable name used is actually a Ruby keyword, and thus causes syntax errors. At the top of each file, there is a warning stating that the files are generated 100% by the ZPROJECT, and shouldn't be modified, but that I should check the README for how to make permanent changes. I couldn't find any information in the README related to that. Aside from that main issue, I also have a few questions:

1) How would I go about submitting a patch for this? Is there some automatic generation of these files, or can I simply make the changes and submit a pull request?
2) Is there a reason CZMQ maintains these bindings, but does not create/maintain a gem for it? There are a few other bindings documented, but there 1-2 years old, or are native extensions (making them less portable than FFI).

**Comment by Asmod4n** [comment]
You can find the api definition for the bindings here: https://github.com/zeromq/czmq/tree/master/api, the code generators for the bindings, where the changes should be made are here: https://github.com/zeromq/zproject/blob/master/zproject_bindings_ruby.gsl

The python bindings had a similar issue, the workaround was to prefix keywords: https://github.com/zeromq/zproject/blob/master/zproject_bindings_python.gsl#L116

**Comment by jemc** [comment]
> Is there a reason CZMQ maintains these bindings, but does not create/maintain a gem for it?

Actually, the reason is because no one has ever put any real effort into the Ruby bindings for CZMQ yet.  There are Ruby, Python, and QML bindings generated for any C project using zproject with XML API definitions.  Other than writing the XML definitions, these bindings are generated "for free" by zproject.  Someone has put time and effort into making sure the Python bindings are usable in CZMQ, but no one has done so for the Ruby bindings for CZMQ yet.  However, I did most of the work on the Ruby bindings generator and I have been actively using the generated bindings for several other projects (just not CZMQ), so they should be sound in general, but you may run into occasional issues like the keyword related issues you mentioned.

I can make a fix today for the keyword issues you've encountered, and I'll post an update in this issue ticket when it's done.

As far as packaging it as a gem goes, there are some reasons this will never be fully automatic, I believe.  As you mentioned, there are also several other sets of bindings for CZMQ available which are handwritten and predate these bindings (@Asmod4n actually maintains one of them) so if we were to package this as a gem we would need to find a unique gem name that does not collide.  Also, another issue is that these bindings will always track with latest `master` of CZMQ, so it may be difficult for people to use the gem with past stable releases.  These issues, when collected together I think make the problem of packaging as a gem nontrivial, but not necessarily prohibitive, if someone had the motivation to come up with a solution.

**Comment by jemc** [comment]
I should also mention that these bindings are not necessarily idiomatic, and are probably easiest to use when wrapped in an additional handwritten layer.  However, they do solve the problem of writing a lot of low-level FFI code so that no one has to maintain that part by hand.

**Comment by rfestag** [comment]
Thanks for the responses. I wasn't aware that @Asmod4n was maintaining one. I've only looked into https://github.com/methodmissing/rbczmq (native, no FFI bindings) and https://github.com/mtortonesi/ruby-czmq (hasn't been updated in about a year, and references removed API methods, so it doesn't work without modification). I started doing the FFI myself, but then noticed there already were bindings written here and decided to play with them instead.

Understood about the gem, and I agree it wouldn't make sense to have it automatically be generated/released. I was actually thinking about just adding a gemspec for these FFI bindings, which could be used to release new gems manually as appropriate. The version.rb would track with the CZMQ version, with an additional patch version on the end (ie, 3.0.3.0, 3.0.3.1, etc). That would allow users to specify the version of the gem that is compatible with their installed CZMQ library. It would be up to the maintainer to basically update the version and manually upload the gem when a new release is tagged. Doesn't seem too horrible to maintain. Am I missing something in the complexities of it?

I absolutely agree that these FFI bindings aren't ideal for direct use in most cases...instead, it should be used by some higher level gem (abstracting away the complexities of FFI maintenance, which I've only just started to appreciate).

**Comment by jemc** [comment]
Note that the keyword issue has been fixed now that https://github.com/zeromq/czmq/pull/1063 is merged.

**Comment by Asmod4n** [comment]
I pretty much gave up on my binding, the ffi handling part was super complex when i started it.
Which has now been solved by czmq itself (thanks for that :)

You either had to write hundred of lines of ffi code for each czmq class or write up the abomination i came up with which is super inflexible to changes made to czmq.

Maybe i will repurpose it to use the ffi handling code czmq now offers.

Though free well to use the high level code i have written in your binding :)

**Comment by Asmod4n** [comment]
Oh, my binding is over at https://github.com/Asmod4n/ruby-ffi-czmq

**Comment by paddor** [comment]
This should be solved by the commit zeromq/zproject@7caf51cd17d9b158eca20402cfcefde812bf5e9e.
