### ISSUE TITLE
free() is used instead of zstr_free(), as the documentation advises

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1155]
For example `zsock_bind()` uses `zsys_vprintf()`. The documentation for `zsys_vprintf()` says `[...]  Free the returned string using zstr_free().`, but actually it uses a plain `free()`. I see that `zstr_free()` doesn't a whole lot more, but I guess this is a code smell. Not sure though. I'm not a C expert.

Same in `zsock_unbind()`, `zsock_connect()`, and `zsock_disconnect()`.

**Comment by jemc** [comment]
Feel free to file a PR.

The only difference between `zstr_free` and `free` is that `zstr_free` will nullify the caller's reference as a convenient way to prevent common code mistakes (using a reference after freeing it, because doing so could sometimes point to garbage data if that address has already been reused).

So `zstr_free` isn't strictly necessary if you're sure you're not making such mistakes, but could still be considered good practice to prevent issues with refactoring.

Please feel free to file a PR if the use of `free` in these places bothers you.  In this community, the burden of improvement is usually on the person who has an issue with the particular problem.  In return, we are always quick to merge improvements.

**Comment by paddor** [comment]
Sure, will do! Thanks for the explanation. I just wasn't really sure if that was done by design.

**Comment by jemc** [comment]
Yep, feel free to ask any more questions in the future as well.

**Comment by hintjens** [comment]
It's critical for apps that use czmq to call zstr_free, in Windows using
czmq as a dll.

**Comment by hintjens** [comment]
Sorry, was on my phone.

On Windows, when using DLLs, you must free objects via the DLL that
allocates them. So if a CZMQ method returns a fresh string, you MUST free
it by calling zstr_free. We adopt the same convention internally except in
local code (allocate and free within a single method) so that apps which
copy code out of CZMQ don't get it wrong.
