### ISSUE TITLE
Cannot compile due to more strict zcert interface

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1230]
Apparently, the new generated C interface of zcert is more strict. When compiling CZMQ, I get:

```
make
Making all in doc
make[1]: Nothing to be done for `all'.
  CC       src/src_libczmq_la-zactor.lo
  CC       src/src_libczmq_la-zauth.lo
  CC       src/src_libczmq_la-zarmour.lo
  CC       src/src_libczmq_la-zbeacon.lo
  CC       src/src_libczmq_la-zcert.lo
src/zcert.c:240:60: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
                zcert_set_meta (self, zconfig_name (item), zconfig_value (item));
                                                           ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [src/src_libczmq_la-zcert.lo] Error 1
make: *** [all-recursive] Error 1
```

[Here](https://github.com/zeromq/czmq/commit/085deec971eaeb952cf13fa2d6509d98dc1571ad#diff-6270c37246eefa96a34041ff22c798e4R58) is the relevant line in the commit that changed the interface.

And [here](https://github.com/zeromq/czmq/blob/master/src/zcert.c#L240)'s the line that tries to use the function.

I have no idea how to fix this.

**Comment by jemc** [comment]
Basically, the compiler is wanting to statically verify the types in the format string, but this is not possible when the string is not a string literal.  Also, this would lead to reaching outside of safe memory if the string given by `zconfig_value(item)` contained any format characters (like `%s`), because it would indicate additional arguments that aren't there.

FYI: the easiest way to do this is:
```c
// Change this:
zcert_set_meta (self, zconfig_name (item), zconfig_value (item));
// To this:
zcert_set_meta (self, zconfig_name (item), "%s", zconfig_value (item));
```

This way, the format string indicates that a single string follows in the varargs, and that single string is the entire resulting string.

I can make the change later tonight if no one else has done it by then.

**Comment by paddor** [comment]
Thanks for the explanation. Makes sense. I've seen this before.

So I discovered a security issue by generating the zcert interface! :laughing: 

I'll fix it, try again, and fix other issues like this ...

**Comment by jemc** [comment]
> So I discovered a security issue by generating the zcert interface

Yep, and this is something pretty wonderful about generated code - with a correct model and a correct generator, you get correct generated application code - a great cure for those little human mistakes that plague us.

**Comment by paddor** [comment]
These should be all. Compiling succeeds.
