### ISSUE TITLE
README.md / Building on Windows needs to be updated

### ISSUE THREAD

**Issue by vtellier** [zeromq/czmq#1401]
Hi,

While trying to compile on Windows I followed the steps of the README.md, but I got stucked.

```
git clone git://github.com/zeromq/czmq.git
cd czmq\builds\msvc
configure.bat
cd build
buildall.bat
```

The folder build doesn\t exists anymore since the commit hintjens@ef4386fd8d1e4dc8b315640099748d2f2dc23145.

> This tree contains a mix of zproject generated files, MSVC produced
> files, and hand-made files. This is unmaintainable.
> 
> Solution:
> - ignore ALL MSVC generated files in .gitignore
> - generate all necessary files in zproject (such as build.bat)
> - delete the rest here

It would be nice to more details about that in README.md

**Comment by ahmetkakici** [comment]
Hello @vtellier,
You don't need build folder, just change directory to the version you want to build for.
For example, you can execute below steps to build for vs2013.


```
git clone git://github.com/zeromq/czmq.git
cd czmq\builds\msvc
configure.bat
cd vs2013
build.bat
```

**Comment by sappo** [comment]
@vtellier does it work the same for libzmq?

**Comment by sappo** [comment]
Sorry @vtellier I meant to address @ahmetkakici.

**Comment by ahmetkakici** [comment]
@sappo i've build both libzmq and czmq vs2013 solutions on my windows machine, what is the problem you've encountered?

**Comment by sappo** [comment]
@ahmetkakici no problem! I'd liked to confirm the build process though before updating the README.

**Comment by ahmetkakici** [comment]
@sappo sorry i've been misunderstood. 
libzmq still have build directory and build.bat file, but configre.bat removed from libzmq. 
Let me build both libzmq, libsodium and czmq from scratch and check readme file.

**Comment by sappo** [comment]
@ahmetkakici great thanks!

**Comment by ahmetkakici** [comment]
With https://github.com/zeromq/czmq/pull/1468 I've added buildall.bat file to czmq repository.
No need for updating readme file.

**Comment by xoorath** [comment]
Hey, making note over a year later on this issue... the Readme is also inherently fragile by just suggesting users clone the latest commit from dependent repos.  

Maybe the readme could be updated to:
1) work correctly with the current state of dependent projects, and vs2017.
2) tag specific releases so if it gets run some number of years later (such as my case), it will still work correctly, even if not updated regularly.

I mean this to be a genuine suggestion, not trying to get on anyone's case here. It's a common issue in readme instructions to suggest non-specific versions that will break if not maintained meticulously. 

Cheers ✌️

**Comment by sappo** [comment]
Feel free to send a PR :)

Am 12.12.2017 6:47 nachm. schrieb "xoorath" <notifications@github.com>:

Hey, making note over a year later on this issue... the Readme is also
inherently fragile by just suggesting users clone the latest commit from
dependent repos.

Maybe the readme could be updated to:

   1. work correctly with the current state of dependent projects, and
   vs2017.
   2. tag specific releases so if it gets run some number of years later
   (such as my case), it will still work correctly, even if not updated
   regularly.

I mean this to be a genuine suggestion, not trying to get on anyone's case
here. It's a common issue in readme instructions to suggest non-specific
versions that will break if not maintained meticulously.

Cheers ✌️

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/czmq/issues/1401#issuecomment-351129641>, or mute
the thread
