### ISSUE TITLE
zsys_run_as exits with -1 on Windows even if it's a no-op

### ISSUE THREAD

**Issue by ballan91** [zeromq/czmq#1498]
zsys_run_as is not yet ported to windows, however should not return -1 if the operation was going to be a no-op due to null import parameters, perhaps a test for no-op scenario could be performed at the top level and we could exit early?

This causes an issue particularly in Malamute on Windows right about here [https://github.com/zeromq/malamute/blob/master/src/malamute.c#L88](url)

**Comment by bluca** [comment]
@sappo - AFAIK on Windows the uid/gid cannot be changed unless the password is provided as well, and obviously we don't want to force users to write the password in plaintext config files.
So I'd argue that zsys_run_as on Windows should enforce that all arguments _are_ NULL with asserts, and return 0, so that programs like Malamute can be sanely cross-platform. What do you think?

**Comment by sappo** [comment]
Sure, if there is no option to make it work on windows it should not crash. The question is though will be program fail anyhow if the command didn't do anything but return successful.
