### ISSUE TITLE
Problem: MSVC2013 build.bat fails on project czmq_selftest with link error

### ISSUE THREAD

**Issue by rodrigomadruga** [zeromq/czmq#1617]
Running `msvc\vs2013\build.bat` fails on czmq_selftest project with the following link error:

`czmq_selftest.obj : error LNK2001: unresolved external symbol _czmq_private_selftest `

Using latest czmq from git, Windows 10 Pro x64.

Related build.log output:

```
Project "C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq.sln" (1) is building "C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\czmq_selftest.vcxproj" (4) on node 1 (default targets).
LinkageInfo:
  Linkage-czmq: dynamic
  Linkage-libzmq: dynamic
PrepareForBuild:
  Creating directory "DebugDEXE\".
  Creating directory "DebugDEXE\czmq_selftest.tlog\".
InitializeBuildStatus:
  Creating "DebugDEXE\czmq_selftest.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /IC:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\..\..\..\..\..\libzmq\include\ /IC:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\..\..\..\..\..\czmq\include\ /Zi /nologo /W3 /WX- /MP /Od /Oy- /D _CONSOLE /D _DEBUG /D UNICODE /D _UNICODE /D WIN32 /D _WIN32 /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Fo"DebugDEXE\\" /Fd"DebugDEXE\vc120.pdb" /Gd /TC /analyze- /errorReport:queue ..\..\..\..\src\czmq_selftest.c
  czmq_selftest.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\DebugDEXE\czmq_selftest.exe" /NOLOGO /LIBPATH:C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\..\..\..\..\..\libzmq\bin\Win32\Debug\v120\dynamic\ /LIBPATH:C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\..\..\..\..\..\czmq\bin\Win32\Debug\v120\dynamic\ libzmq.lib libczmq.lib Iphlpapi.lib Rpcrt4.lib Ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\DebugDEXE\czmq_selftest.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\DebugDEXE\czmq_selftest.lib" /MACHINE:X86 /SAFESEH DebugDEXE\czmq_selftest.obj
  C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\bin\Win32\Debug\v120\dynamic\libczmq.lib
czmq_selftest.obj : error LNK2001: unresolved external symbol _czmq_private_selftest [C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\czmq_selftest.vcxproj]
C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\DebugDEXE\czmq_selftest.exe : fatal error LNK1120: 1 unresolved externals [C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\czmq_selftest.vcxproj]
Done Building Project "C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq_selftest\czmq_selftest.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\TeamCity\buildAgent\work\d0ebe9b63be6990e\czmq\builds\msvc\vs2013\czmq.sln" (default targets) -- FAILED.

Build FAILED.
```

**Comment by bluca** [comment]
Everything is working on the CI:

https://ci.appveyor.com/project/zeromq/czmq/build/build-826

Are you building with DRAFT APIs? That symbol is still in draft state

**Comment by rodrigomadruga** [comment]
Yes, building with DRAFT APIs, as it is set if `.git` is found in configure.bat:

```
:-  Check if we want to build the draft API
if "%1" == "--enable-drafts" goto :with_draft
if "%1" == "--disable-drafts" goto :no_draft
IF NOT EXIST "..\..\.git" GOTO no_draft
```

If I run `configure.bat --disable-drafts`, `platform.h` undefs CZMQ_BUILD_DRAFT_API but I get a lot of compile errors, in `ztimerset.c` and `ztrie.c`. These two classes are in DRAFT state correct?

Is there a step to regenerate the `libczmq.vcxproj` that I am missing?

Is the CI build using cmake to generate czmq.sln and vcxproj files also?

**Comment by bluca** [comment]
ztimerset and ztrie are draft yes
The CI is using CMake but that's the extent of my knowledge of the windows side, sorry
@bbdb68 do you have any suggestion?

**Comment by twhittock** [comment]
The pre-generated visual studio solutions have to make a decision about
whether to include draft files or not.

In theory we could use some conditionals or project configurations to
choose between the 2 states, but it doesn't at the moment. This is a defect
in zproject I guess. Workaround is to use CMake.

**Comment by evoskuil** [comment]
The proper VS approach is to expose the optional configuration using a *property* that sets a preprocessor define. This is exposed in the VS UI via an XML extension and accessible to builds via the build command line.

**Comment by rodrigomadruga** [comment]
I made a PR (#1619) with the changes proposed, following @evoskuil suggestion. 

But the link error still exists when compiling with drafts-api enabled. Still investigating.

**Comment by mlodew** [comment]
The Link error is due to source files czmq_private_selftest.c and zgossip_msg.c missing in the visual studio project. Once added as additional source files to the visual studio project, compilation works. Unfortunately I don't know how to add them to the zproject configuration as czmq_selftest is not explicitly mentioned in project.xml but seems to be somehow implicitly added. Could someone point me into the right direction?

**Comment by jacktrades52** [comment]
To elaborate on mlodew's comment.  If compiling from the command line, add the following lines to the czmq_selftest.vcxproj file in the czmq_selftest directory for your msvs version:

<ClCompile Include="..\..\..\..\src\czmq_private_selftest.c" />
<ClCompile Include="..\..\..\..\src\zgossip_msg.c" />

I added mine after the line

<ClCompile Include="..\..\..\..\src\czmq_selftest.c" />

As mlodew mentions, compilation works after that.  Thanks mlodew for your temp workaround until this issue is resolved.

**Comment by jacktrades52** [comment]
To elaborate on mlodew's comment. If compiling from the command line, add the following lines to the czmq_selftest.vcxproj file in the czmq_selftest directory for your msvs version:

`<ClCompile Include="..\..\..\..\src\czmq_private_selftest.c" />`
`<ClCompile Include="..\..\..\..\src\zgossip_msg.c" />`

after the line

`<ClCompile Include="..\..\..\..\src\czmq_selftest.c" />`

As mlodew mentions, compilation works after that. Thanks mlodew for your temp workaround until this issue is resolved.

**Comment by bluca** [comment]
This is how it was handled for other build systems:

https://github.com/zeromq/zproject/commit/9714a1d433965a09221055b50a4a24bb5c3891c5

**Comment by sgluss** [comment]
I had this same problem, @jacktrades52 fix worked for me on windows 10 with VS2017
