### ISSUE TITLE
Documentation for building on Windows

### ISSUE THREAD

**Issue by RSFalcon7** [zeromq/czmq#1626]
Well congratulations, czmq looks like great lib and I'm looking forward to use it.

Two issues regarding doc to build on windows:

 * The [official site says that the last stable is 4.0.3](http://czmq.zeromq.org/page:get-the-software), but the repo seems to go until 4.0.2.
 * The `builds` dir reffered in [here](https://github.com/zeromq/czmq#building-on-windows) doesn't exist on the oficial zip/tar.gz files, I had to download the github repo to build it.

**Comment by sappo** [comment]
Hi Rafael,
thanks for reporting. The version mismatch is a typo I'll fix it tomorrow.
Regarding the windows build. The documentation on czmq.zeromq.org is a bit
outdated. You always can find the latest and greatest documentation in the
README.md on GitHub.

//Kevin

Am 16.02.2017 20:43 schrieb "Rafael Silva" <notifications@github.com>:

Well congratulations, czmq looks like great lib and I'm looking forward to
use it.

Two issues regarding doc to build on windows:

   - The official site says that the last stable is 4.0.3
   <http://czmq.zeromq.org/page:get-the-software>, but the repo seems to go
   until 4.0.2.
   - The builds dir reffered in here
   <https://github.com/zeromq/czmq#building-on-windows> doesn't exist on
   the oficial zip/tar.gz files, I had to download the github repo to build it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/czmq/issues/1626>, or mute the thread

**Comment by sappo** [comment]
@RSFalcon7 regarding your second issue. The steps in the README are copied from the libzmq mechanism which should have been ported to czmq but somehow they weren't. There are build scripts withing the vs folder which should work (sorry I don't own a windows machine). If you like czmq we really appreciate pull requests optimizing our build system especially for windows. Adopting the windows build from libzmq (https://github.com/zeromq/libzmq/tree/master/builds/msvc) would be great.
