### ISSUE TITLE
Problem: zloop is using reader callback after zloop_reader_end

### ISSUE THREAD

**Issue by piskorzj** [zeromq/czmq#1634]
I've recently hit a problem when I have zloop with timer and reader. And inside timer I'm doing zloop_reader_end. All works well until both conditions are met in one zloop go - timer is expired and data is available on reader. In timer after zloop_reader_end I'm also doing zsock_destroy and other cleanup stuff. Thus callback called for socket contains invalid data - I don't want it to be called after doing zloop_reader_end cause it breaks whole loop logic.

Any suggestions how to avoid this or zloop implementation needs to be changed?

**Comment by bluca** [comment]
You get a reference to the socket in the callback, can't you simply check if it's still valid and return if not?

**Comment by piskorzj** [comment]
@bluca How would you see checking socket in callback when zloop on pollset rebuild is making copy of reader struct (as far as I can tell from code here https://github.com/zeromq/czmq/blob/master/src/zloop.c#L265)?

Something like:
`
if(self->need_rebuild)
    continue;
`
after timers to skip rest of processing and start poll again?

**Comment by bluca** [comment]
zmq_poll is edge triggered so skipping and going back into it while there's still data to read would be wrong, since it would not return anymore until new data is available

See: https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/

**Comment by piskorzj** [comment]
Ok, then this https://github.com/zeromq/czmq/blob/master/src/zloop.c#L795 is also invalid, isn't it?

**Comment by pijyoi** [comment]
It's the ZMQ_FD notification socket that is edge triggered. zmq_poll() can
be used in a level triggered fashion.

zmq_poll() does this by checking ZMQ_EVENTS before doing any poll/select on
the ZMQ_FD.

On 7 Mar 2017 9:08 p.m., "Luca Boccassi" <notifications@github.com> wrote:

zmq_poll is edge triggered so skipping and going back into it while there's
still data to read would be wrong, since it would not return anymore until
new data is available

See: https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zeromq/czmq/issues/1634#issuecomment-284716570>, or mute
the thread

**Comment by bluca** [comment]
@piskorzj you are right indeed, got confused for a moment

**Comment by piskorzj** [comment]
Ok :)
I'm writing now test case catching my issue and I'll add that lines with continue to check if it fixes it. Then I'll make pull request.

**Comment by bluca** [comment]
perfect, thanks

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1635
