### ISSUE TITLE
zeromq-4.1.4 Memory leak

### ISSUE THREAD

**Issue by Little-Blue-Hat** [zeromq/czmq#1639]
I am using this version, running about half a day or so, that the memory usage rate of about 10%, about 30% hours a day, if I set the thread much more memory, this is the memory leak? Help me. Thanks

**Comment by sappo** [comment]
Hi @Little-Blue-Hat,
we need a bit more information about your program in order to give you some advice. A minimal code sample that causes the memory leak would be great. Otherwise did you try to chase the memory leak with valgrind. If you're using zproject you can run your tests with valgrind `make memcheck`.

**Comment by bluca** [comment]
Also this is not the right repository for zeromq 4.1.4, which is also very old

**Comment by Little-Blue-Hat** [comment]
Oh, thank you. I think I'm in the wrong place. I should go to libzmq。
