### ISSUE TITLE
Missing library in python binding on Windows

### ISSUE THREAD

**Issue by diorcety** [zeromq/czmq#1682]
In the python binding code there is
libcpath = find_library("c")
Such library doesn't exist on pure Windows (without mingw or anything else)

**Comment by twhittock** [comment]
ctypes' find_library is defined with the following shim on Windows:

        if name in ('c', 'm'):
            return find_msvcrt()

**Comment by diorcety** [comment]
Linked to https://bugs.python.org/issue23606

**Comment by diorcety** [comment]
Maybe we should use zstr_free ?

**Comment by diorcety** [comment]
https://github.com/diorcety/czmq/commit/16074a095188df905c572ae32fa20ebba0717578

**Comment by twhittock** [comment]
Sadly this change only works for CZMQ, and that file is auto-generated from zproject. It's a good temporary solution for this project, but sadly isn't workable for other zproject-based projects.

I don't see an actual solution recommended by the python bug ticket - did they seriously just break Windows ctypes projects which use C stdlib functions without even an attempt at an upgrade path, and without any release notes?

I don't understand their reservations regarding the msvcrt object they expose - surely the parameter and restypes *should* be shared since the signatures should always be the same? Do the cffi python bindings also have this problem?

**Comment by diorcety** [comment]
Maybe a better solution for "fresh" pointer is to provide in the api the free function associated. For example il the api:https://github.com/zeromq/czmq/blob/master/api/zstr.api#L13
