### ISSUE TITLE
Don't undef _WIN32_WINNT

### ISSUE THREAD

**Issue by diorcety** [zeromq/czmq#1699]
If the user set an _WIN32_WINNT definition we should avoid to change it.
https://github.com/zeromq/czmq/blob/master/include/czmq_prelude.h#L241

**Comment by diorcety** [comment]
Added to this. There is a way to support windows XP. The only missing function is if_nametoindex. we can emulate it like glib did https://github.com/GNOME/glib/blob/017f78d77f0bf2bed749e21199ea89d75e56ab69/gio/gsocket.c#L2159

**Comment by sappo** [comment]
@diorcety windows XP is end of support, not sure it's worth supporting.

**Comment by evoskuil** [comment]
@sappo, Windows XP is still widely utilized and MSFT still sells support packages for it. It was the only version of Windows I casually observed in use in a recent trip to several African countries. Due to extensive piracy of XP [estimates](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers) are hard, but it appears to be at about 4% of desktops globally and as high as 11% in Africa. I recommend maintaining support at the level of XP SP2 (which is a major distinction from versions prior).

**Comment by bluca** [comment]
Yeah (unfortunately!) XP is widely used still. #1701 should fix it.

**Comment by diorcety** [comment]
#1701 remove some features. We can support these without much code, cf https://github.com/diorcety/czmq/commit/6e24dca723fc7f2fc96eb96cba3609491f294f67 https://github.com/diorcety/czmq/commit/b6ebdfed07a6b3260ae620f2ca46a1ce4d25983b

**Comment by bluca** [comment]
I don't think there's any point - IPv6 multicast for zbeacon is not supported on Windows anyway.

Also - is that code from glib? If so first of all you must ensure that the licenses are compatible, and then you must attribute it.

**Comment by diorcety** [comment]
sure
