### ISSUE TITLE
Functional difference between release & debug builds.

### ISSUE THREAD

**Issue by Formulator** [zeromq/czmq#1781]
I’ve been testing https://github.com/zeromq/czmq/blob/master/examples/security/ironhouse2.c on both Windows 10 and Ubuntu 16.04.

On BOTH operating systems using an IDE I have noticed that the ‘debug’ version of the ironhouse2.c program runs properly, I get "Ironhouse test OK"; however the ‘release’ version doesn’t run to completion on either system; there is no output to the console.

Environments;
Windows 10, Visual Studio 2013, using NuGet CZMQ package; https://www.nuget.org/packages/czmq_vc120/ czmq_vc120 -Version 3.0.2
 
Ubuntu 16.04, Codelite IDE ver. 11, using CZMQ built from cloned git repository; https://github.com/zeromq/czmq

Because this behaviour is apparent using different versions of CZMQ & different IDE & different OS I’m guessing it’s more than coincidence.

Anyone know what’s going on here?

**Comment by bluca** [comment]
By "debug" and "release", what do you mean exactly? Is your "release" config by any chance stripping out asserts?

If it does, it shouldn't - for example it will remove all these function calls:

https://github.com/zeromq/czmq/blob/master/examples/security/ironhouse2.c#L68

Note that we don't have any debug/release different settings, and it's intentional.

**Comment by evoskuil** [comment]
A "debug" build in VC++ is simply a build that defines `_DEBUG`, generates symbols for debugging, and may disable optimizations that hinder debugging. In zeromq this is controlled entirely by the Debug.props file, which contains the following:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <ImportGroup Label="PropertySheets">
    <Import Project="Common.props" />
  </ImportGroup>
  
  <PropertyGroup>
    <_PropertySheetDisplayName>Debug Settings</_PropertySheetDisplayName>
    <DebugOrRelease>Debug</DebugOrRelease>
  </PropertyGroup>
  
  <ItemDefinitionGroup>
    <ClCompile>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <Optimization>Disabled</Optimization>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <ResourceCompile>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>    
  </ItemDefinitionGroup>
  
</Project>
```

**Comment by Formulator** [comment]
@bluca The 'debug' or 'release' settings are simply selected in the IDE before pressing 'build', I'm just going with whatever compiler settings are enacted by changing that setting; I have no detailed knowledge of the exact optimizations or other changes which are made.  Could it be that asserts are stripped out? Possibly, but I have no idea how to change or test that.  This issue is what a user is going to encounter when trying to build an application with CZMQ and be left wondering what is wrong? Why won't the application work!

**Comment by evoskuil** [comment]
zeromq style asserts would not be removed by the compiler, as these are not conditionally-compiled on a DEBUG symbol. zeromq asserts are actually exception-throwing functions that are unconditionally defined.

**Comment by bluca** [comment]
> @bluca The 'debug' or 'release' settings are simply selected in the IDE before pressing 'build', I'm just going with whatever compiler settings are enacted by changing that setting; I have no detailed knowledge of the exact optimizations or other changes which are made. Could it be that asserts are stripped out? Possibly, but I have no idea how to change or test that.

Try to add to the very top of the examples code:

```
#ifdef NDEBUG
#undef NDEBUG
```

> This issue is what a user is going to encounter when trying to build an application with CZMQ and be left wondering what is wrong? Why won't the application work?

No, this is just the example code that does something a bit questionable - calling functions from inside assert(). As the name suggests it's just an example.

**Comment by Formulator** [comment]
@bluca 

`#ifdef NDEBUG

#undef NDEBUG

#endif`

made the difference on Windows; debug & release versions now functional.  Will check on Ubuntu later.

May I say that the examples should be....ahem; foolproof.  People like me use them to learn! ;-)

**Comment by bluca** [comment]
I guess no developer used one of those IDEs that set those defines with those examples. Could you please send a PR with the change?

**Comment by jimklimov** [comment]
Just in case, also note that when I had MSVC experience back in school almost a couple of decades ago, there was notable difference where DEBUG builds made a clean-lab environment for the run, zeroing out new variables and stuff, while RELEASE builds did not. So when we had uninitialized variables, the release builds behaved funny and failed, but we could not track it down using the debugger ;)

Not sure if this note is relevant today, but better be warned ;)

**Comment by evoskuil** [comment]
As a general rule it is best to avoid conditional code as much as possible. More code paths to test means more stuff probably note tested. The use of conditionally-excluded debug code in VC++ projects commonly produces behavioral differences. The most notable is the use of ASSERT macros.

The common purpose of an assert is to test developer assumptions. In other words, they are never supposed to fail, but when they do it's an indication of a code error. Since they aren't ever supposed to fail, they can logically be compiled out. This is the intent of assertions, however they are more often than not misused as error handling. If termination is desired in the case of a possible error, then to throw or abort is the correct pattern, since it is not expected to be compiled out.

The use of the term `assert` in zeromq is unusual in that it's actually a complex throw or abort. If it was up to me I would rename all of the asserts to eliminate the term, since there are no actual assertions in zeromq.

**Comment by Formulator** [comment]
Perhaps the answer is to simply write a comment in the example code outlining the issue and indicating the fix so that the interested user can quickly overcome the problem?  No added complexity.

**Comment by bluca** [comment]
We already undefine NDEBUG in code that gets included in other projects (eg: zproto generate engines), but feel free to send a PR with the fix that you prefer
