### ISSUE TITLE
Windows Build reference is lacking/invalid

### ISSUE THREAD

**Issue by sheinbergon** [zeromq/czmq#1925]
This is not the same as #1917 

The final steps in the windows build guide are 

```
   git clone git://github.com/zeromq/czmq.git
    cd czmq\builds\msvc
    configure.bat
    cd build
    buildall.bat
    cd ..\..\..\..
```

However:
- build directory is missing (and has been like this for the past 3 years)
- Trying to build directly via visual studio (retargeting 2015 to newer version) complains about missing libmqz.import.props

Please advise.

**Comment by Slesa** [comment]
+1

**Comment by ozzynator** [comment]
Trying to build directly via VS2017 complains about missing libmqz.import.props here, too. The build.batch script will also not work, as it crashes with
```
*** ERROR, build tools not found: Microsoft Visual Studio 14.0\VC\vcvarsall.bat
```
which makes sense, because Visual Studio 2017 has a different folder structure ( [SO Post](https://stackoverflow.com/questions/43372235/vcvarsall-bat-for-visual-studio-2017/44868146#44868146) )

It seems that its not so easy to retarget CZMQ for VS2017. Not sure how well this works, when you build the library with VS2015 but everything else with VS2017..
