### ISSUE TITLE
pkg-config cannot find zmq package

### ISSUE THREAD

**Issue by somdoron** [zeromq/czmq#1944]
I have libzmq installed from master and czmq installed from master.
When I try to use pkg-config to find the czmq library (`pkg-config --modversion libczmq) I'm getting the following error:

```
Package zmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `zmq.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zmq', required by 'libczmq', not found
```

When I edit `/usr/local/lib/pkgconfig/libczmq.pc` and change zmq to libzmq everything works.

Using Fedroa 29 and pkgconfig version 1.5.3

**Comment by somdoron** [comment]
Content of the libczmq.pc file:

```
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libczmq
Description: The high-level C binding for 0MQ
Version: 4.2.0

Requires:zmq

Libs: -L${libdir} -lczmq
Cflags: -I${includedir} -DCZMQ_BUILD_DRAFT_API=1
Libs.private:  -lzmq -luuid  -lsystemd 

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
```

**Comment by bluca** [comment]
That's weird, the one we build and that fedora ships definitely says Requires:libzmq

**Comment by bluca** [comment]
eg: https://kojipkgs.fedoraproject.org//packages/czmq/4.0.2/7.fc29/x86_64/czmq-devel-4.0.2-7.fc29.x86_64.rpm

```
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: libczmq
Description: The high-level C binding for 0MQ
Version: 4.0.2

Requires:libzmq

Libs: -L${libdir} -lczmq
Cflags: -I${includedir} 
Libs.private:  -lzmq  -luuid 

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
```

Where are you getting czmq from?

**Comment by somdoron** [comment]
master, up to date with latest commit

**Comment by somdoron** [comment]
weird, removing `src/libczmq.pc` and running ./configure again solved the problem

**Comment by somdoron** [comment]
thanks

**Comment by bluca** [comment]
Did you have at some point libzmq installed _without_ its pkgconfig file in place?

https://github.com/zeromq/czmq/blob/master/configure.ac#L221

It probably found the library and used the linkname, I'm not sure that else clause is correct

**Comment by somdoron** [comment]
Yes! 

I ran ./configure on czmq before I had PKG_CONFIG_PATH configured to the /usr/local/lib/pkgconfig.

**Comment by jimklimov** [comment]
Just in case, a copy of my reply:

----

I have no strong opinion on that... how would `pkg-config` behave if the string is empty? Also, just in case: isn't the root cause that the name can not be detected (correctly?) for whatever reason?




Taking a second look at this, and at the example from @somdoron maybe the problem is with linkname (`zmq` in `-lzmq`) rather than libname. And this strikes in the `yes` case, so the library was detected. Probably a proper way forward would be to somehow query pkg-config for the config name of the said library, if that's possible?




That said, I'm not sure OTOH what the `Requires:` line in `.pc` refers to - if it is a distro-dependent package name or author-defined metadata name (basename of that other project's `.pc` file) or the name derived from project or lib name in zproject generations, we can not really guess it in the general case (can have distro maintainers use a configure flag and/or default to the redhat/debian value from project.xml if provided - or defaulted there otherwise)... Or maybe if the empty value would skip the Requires line altogether, we would at least not refer to an unknown package (but might fail some auto-dependencies elsewhere?)




On Mon, Nov 5, 2018 at 1:25 PM Luca Boccassi <notifications@github.com> wrote:

@jimklimov I think this should be empty - if the pkg-config metadata name cannot be found, then adding an incorrect one will make it fail. See zeromq/czmq#1944

**Comment by bluca** [comment]
The Requires: refers exactly to the name of the .pc file, not to the library name. They might be the same or they might be different. But the important thing is that if a Requires cannot be found, the call will fail. If it's empty, then it's just skipped.

The right thing in case the Requires cannot be figured out, is to simply add the linker flag in Libs.

**Comment by bluca** [comment]
Actually not even that, as the Libs is what a third program needs, so it should just do nothing. Will send a PR shortly
