### ISSUE TITLE
target install fails on std::nothrow

### ISSUE THREAD

**Issue by eninyo** [zeromq/czmq#2011]
hello,
i using czmq 4.2.0 (the latest release).
i saw this issue as part of stuff that was fixed already in 2014.
but it happen to me also now, although 4.2.0 is from 2019.

i use static build.
i have build my zmq lib as static. and now i want to do the same for my czmq.

i set the zmq lib (the static debug one). 

this is the error i get:
..\libzmq\build\Debug\install\lib\libzmq.a(zmq.cpp.o): In function `zmq_ctx_new':
..\libzmq\src/zmq.cpp:139: undefined reference to `std::nothrow'

i can ofcourse choose to compile the static target of czmq (and it works), but i would like the install target to work too.

anyone know what can i do?

**Comment by jimklimov** [comment]
I would guess your build environment (or version thereof) does not provide
or use a static-lib (non-dll) variant of libstdc++ or some such. Maybe also
due to debug vs release.

I think if you build a static lib, it can not record refere ces to dynamic
ones directly - rather its consumers (binaries and other libs) should do so
at link time. Try to play with `-l` options, or what MSVS (I assume) uses
these days.

Jim
