### ISSUE TITLE
ci_deploy_obs.sh fails

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#2055]
When creating a new release the automatic release fails due to an error in the `ci_deploy_obs.sh` script. Sadly the script does not log any information as to why it is failing. See the failing travis job: https://travis-ci.org/zeromq/czmq/jobs/651654150?utm_medium=notification&utm_source=github_status

@bluca could you check this when you got time.

**Comment by bluca** [comment]
I'll add it to my list - it's very sensitive to timing changes unfortunately

**Comment by bluca** [comment]
The main problem is that we have to do an awkward dance to switch the latest_release branch to the latest tag, which is asynchronous, since we can't change the _service file on OBS to point to the latest tag automatically. This always fails due to timing.

So I've implemented @PARENT_TAG@ in the OBS git service, which allows to always fetch the most recent tag - this will remove the need for the workaround, and should be much more reliable:
https://github.com/openSUSE/obs-service-tar_scm/pull/359
Once that is merged I'll update the scripts.
