### ISSUE TITLE
zsys_shutdown() assert on zsys_error()

### ISSUE THREAD

**Issue by zzm3145** [zeromq/czmq#2084]
Related to 32151ff
When zsys_shutdown() find dangling socket, it will call zsys_error().  Then s_log() will try to reinit zsys, assert on existing  s_process_ctx.

example:
int main()
{
    zsys_init();
    zsock_t* s = zsock_new(ZMQ_DEALER);
    zsys_shutdown();
    return 0;
}

**Comment by zzm3145** [comment]
If the log system should only be used in inited zsys, then the fix may be using normal printf in  zsys_shutdown() to indicate errors, rather than revert 32151ff.

**Comment by sappo** [comment]
Thanks for providing the minimal example.

The error message printed is correct because you didn't destroy all sockets before calling `zsys_shutdown`

Also a manual call to `zsys_shutdown` is only required on windows. On other systems it is implicitly called whenever the last tracked socket gets destroyed.
