### ISSUE TITLE
./configure failed to find libzmq

### ISSUE THREAD

**Issue by fweckesser** [zeromq/czmq#839]
I am running on Centos 6.5 and 7.0. I recently did a fresh clone of both libzmq and czmq.  They used to build perfectly per the install instructions. libzmq still builds fine using the install instructions, however czmq no longer gets past the configure pass.

For libzmq I ran autogen, configure, make, sudo make install and sudo ldconfig with no errors.  When i went to build czmq i ran autogen fine, but configure fails with the following.

checking for zmq... no
configure: error: Package requirements (libzmq) were not met:

No package 'libzmq' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables zmq_CFLAGS
and zmq_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

I can play with PKG_CONFIG_PATH and the zmq variables if that is the recommended solution,  but this used to work without those changes.

Thanks

**Comment by twhittock** [comment]
It sounds like centos doesn't have a config.site set up in /usr/local/share/config.site (or local/etc) to export PKG_CONFIG_PATH - this could be because they don't want/expect users to install things manually there, as it's reserved for RPM based installations? Maybe they'd expect people to build into their own prefix?
