### ISSUE TITLE
Problem: working with certs requires file system interaction.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#995]
Currently the only non-deprecated way to save and load certs is via a file system path. This combined with lack of Windows Unicode support prevents use of certs for Windows platforms.

`zcert_fprint (zcert_t *self, FILE *file)` is commented as `DEPRECATED as incompatible with centralized logging` although I can't figure out what could be hitting logging given that the stream is parameterized.

Use of streams would allow the file name to be removed from the equation, and also enable emitting certificates via stdio, which is one of our scenarios. The current model of using paths is pretty hacky for us. So I'd like to add stream-based overloads but they appear to be frowned upon. Could someone please clarify?

**Comment by hintjens** [comment]
I deprecated the _fprint methods because they were inconsistent with the
zsys logging infrastructure, which sends log data to a single destination
(system log, socket, or file).

The point being that it's desirable to switch logging destination globally,
not at the level of individual method calls. Otherwise applications are
filled with code to track and pass log file handles.

Note that this a different use case than stdio, which is why the _print
methods are not deprecated. Also, a different use case than reading/saving
from files. The conventional methods for this last one are _load and _save
(which could be extended to take stream handles, for sure).

**Comment by evoskuil** [comment]
OK, so was `zcert_fprint` just caught up in the deprecation of all `_fprintf` methods (it doesn't appear to do any logging itself)?

I'll take a crack at stream-based overrides for `zcert_load`, `zcert_save`, `zcert_save_public` and `zcert_save_secret` (these cover the set of `czmq++` save/load methods).

**Comment by hintjens** [comment]
It's not so much that the method does logging, rather the fprint semantics
were being used for logging and debugging. I was probably being zealous
here...
